### PR TITLE
Add previewSetting.json for size and position of preview window, read…

### PR DESCRIPTION
**Pull request by tilllt**
… and use settings in manualControl.py and GCamera.py

### CODE REVIEW

**Review by meantux — CHANGES_REQUESTED** [review]
Once here I would prefer a dynamic solution where we detect the actual screen resolution and calculate a proper offset.

Also, I'm not sure how the overlay reacts to a change of resolution (the picture I overlay is of a fixed size), this will require some testing from my part.

For a better overlay grid we should stop using the picamera's "start_preview" and make our own thread that grabs the frames individually and "show" them sequentially. so we could draw lines ourselves over each instead of that limited overlay layer. This might be simpler in XWindow mode (easy with opencv's cv2 library),

I could attack this making it a priority, unless you want to take care of it?

**Comment by tilllt** [comment]
You are absolutely right that there is more room for improvement, and actually checking the screen size to do the overlay would be much better. For now I just tried to get rid of having to change the overlay settings in two (hardcoded) places when I download a new version of your code, since the "old" overlay is hard coded in the manualControl and GCamera ... I know extremely little about python programming so if we wanted to do something more complex I probable would need some guidance how to proceed with it. 

The other thing I wanted to try is to use camera.annotate_text to move the menu in manualControl and display it over the preview image, to better use my tiny screen (probably it should be "hideable" as well)

**Comment by tilllt** [comment]
Btw did you see the new libcamera api they released? I think it can be potentially super interesting for our use case in the future, although apparently limited for now:
https://libcamera.org/entries/2020-05-05.html

**Comment by meantux** [comment]
This will be fully addressed in the NEWGUI branch

**Comment by tilllt** [comment]
Sounds great, looking forward to that version

**Pull request closed without merging**
